  version: '3'

  services:
    nginx:
      build:
        context: ./docker/nginx
      volumes:
      - ./:/app
      ports:
      - 8080:80
      depends_on:
        - php-fpm

    php-fpm:
      build:
        context: ./docker/php
      volumes:
        - ./:/app

    mysql:
      image: mysql:5.7
      environment:
        - "MYSQL_ROOT_PASSWORD=root"
        - "MYSQL_USER=symfony"
        - "MYSQL_PASSWORD=symfony"
        - "MYSQL_DATABASE=symfony"
      volumes:
        - mysql:/var/lib/mysql
      ports:
        - "3306:3306"

  volumes:
    mysql:
      driver: local